#SPDX-License-Identifier: MIT-0
---
# tasks file for apache2
- name: stop nginx
  service:
    name: nginx
    state: stopped

- name: Install Apache2
  apt: name=apache2 state=present update_cache=yes
